// flow-typed signature: dca427aff8e0492b24886039894ea9f5
// flow-typed version: <<STUB>>/electron-devtools-installer_v^2.2.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-devtools-installer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-devtools-installer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-devtools-installer/dist/downloadChromeExtension' {
  declare module.exports: any;
}

declare module 'electron-devtools-installer/dist' {
  declare module.exports: any;
}

declare module 'electron-devtools-installer/dist/utils' {
  declare module.exports: any;
}

declare module 'electron-devtools-installer/src/downloadChromeExtension' {
  declare module.exports: any;
}

declare module 'electron-devtools-installer/src' {
  declare module.exports: any;
}

declare module 'electron-devtools-installer/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-devtools-installer/dist/downloadChromeExtension.js' {
  declare module.exports: $Exports<'electron-devtools-installer/dist/downloadChromeExtension'>;
}
declare module 'electron-devtools-installer/dist/index' {
  declare module.exports: $Exports<'electron-devtools-installer/dist'>;
}
declare module 'electron-devtools-installer/dist/index.js' {
  declare module.exports: $Exports<'electron-devtools-installer/dist'>;
}
declare module 'electron-devtools-installer/dist/utils.js' {
  declare module.exports: $Exports<'electron-devtools-installer/dist/utils'>;
}
declare module 'electron-devtools-installer/src/downloadChromeExtension.js' {
  declare module.exports: $Exports<'electron-devtools-installer/src/downloadChromeExtension'>;
}
declare module 'electron-devtools-installer/src/index' {
  declare module.exports: $Exports<'electron-devtools-installer/src'>;
}
declare module 'electron-devtools-installer/src/index.js' {
  declare module.exports: $Exports<'electron-devtools-installer/src'>;
}
declare module 'electron-devtools-installer/src/utils.js' {
  declare module.exports: $Exports<'electron-devtools-installer/src/utils'>;
}
