// flow-typed signature: a908f0a8e370dcd77bb06663615ae4aa
// flow-typed version: <<STUB>>/icepick_v^2.1.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'icepick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'icepick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'icepick/icepick.dev' {
  declare module.exports: any;
}

declare module 'icepick/icepick' {
  declare module.exports: any;
}

declare module 'icepick/icepick.min' {
  declare module.exports: any;
}

declare module 'icepick/icepick.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'icepick/icepick.dev.js' {
  declare module.exports: $Exports<'icepick/icepick.dev'>;
}
declare module 'icepick/icepick.js' {
  declare module.exports: $Exports<'icepick/icepick'>;
}
declare module 'icepick/icepick.min.js' {
  declare module.exports: $Exports<'icepick/icepick.min'>;
}
declare module 'icepick/icepick.test.js' {
  declare module.exports: $Exports<'icepick/icepick.test'>;
}
