// flow-typed signature: 273bfe1a37eecd6c0d22fac2109012d5
// flow-typed version: <<STUB>>/react-photonkit_vhttps://github.com/ihgrant/react-photonkit.git#0.5.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-photonkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-photonkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-photonkit/dist/photon' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/actionbar' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/button-group' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/button' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/checkbox' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/content' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/icon' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/input' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/list-group' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/list-item' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/nav-group-item' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/nav-group' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/nav-title' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/options' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/pane-group' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/pane' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/photon' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/photon' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/radio-group' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/radio' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/tab-group' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/tab-item' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/table' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/textarea' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/toolbar' {
  declare module.exports: any;
}

declare module 'react-photonkit/src/window' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/button-spec' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/form-test' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/list-group-spec' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/nav-group-spec' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/photon-spec' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/tab-spec' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/table-spec' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/test-karma' {
  declare module.exports: any;
}

declare module 'react-photonkit/test/toolbar-spec' {
  declare module.exports: any;
}

declare module 'react-photonkit/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-photonkit/dist/photon.js' {
  declare module.exports: $Exports<'react-photonkit/dist/photon'>;
}
declare module 'react-photonkit/src/actionbar.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/actionbar'>;
}
declare module 'react-photonkit/src/button-group.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/button-group'>;
}
declare module 'react-photonkit/src/button.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/button'>;
}
declare module 'react-photonkit/src/checkbox.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/checkbox'>;
}
declare module 'react-photonkit/src/content.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/content'>;
}
declare module 'react-photonkit/src/icon.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/icon'>;
}
declare module 'react-photonkit/src/input.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/input'>;
}
declare module 'react-photonkit/src/list-group.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/list-group'>;
}
declare module 'react-photonkit/src/list-item.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/list-item'>;
}
declare module 'react-photonkit/src/nav-group-item.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/nav-group-item'>;
}
declare module 'react-photonkit/src/nav-group.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/nav-group'>;
}
declare module 'react-photonkit/src/nav-title.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/nav-title'>;
}
declare module 'react-photonkit/src/options.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/options'>;
}
declare module 'react-photonkit/src/pane-group.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/pane-group'>;
}
declare module 'react-photonkit/src/pane.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/pane'>;
}
declare module 'react-photonkit/src/photon.js' {
  declare module.exports: $Exports<'react-photonkit/src/photon'>;
}
declare module 'react-photonkit/src/photon.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/photon'>;
}
declare module 'react-photonkit/src/radio-group.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/radio-group'>;
}
declare module 'react-photonkit/src/radio.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/radio'>;
}
declare module 'react-photonkit/src/tab-group.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/tab-group'>;
}
declare module 'react-photonkit/src/tab-item.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/tab-item'>;
}
declare module 'react-photonkit/src/table.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/table'>;
}
declare module 'react-photonkit/src/textarea.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/textarea'>;
}
declare module 'react-photonkit/src/toolbar.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/toolbar'>;
}
declare module 'react-photonkit/src/window.jsx' {
  declare module.exports: $Exports<'react-photonkit/src/window'>;
}
declare module 'react-photonkit/test/button-spec.jsx' {
  declare module.exports: $Exports<'react-photonkit/test/button-spec'>;
}
declare module 'react-photonkit/test/form-test.jsx' {
  declare module.exports: $Exports<'react-photonkit/test/form-test'>;
}
declare module 'react-photonkit/test/list-group-spec.jsx' {
  declare module.exports: $Exports<'react-photonkit/test/list-group-spec'>;
}
declare module 'react-photonkit/test/nav-group-spec.jsx' {
  declare module.exports: $Exports<'react-photonkit/test/nav-group-spec'>;
}
declare module 'react-photonkit/test/photon-spec.jsx' {
  declare module.exports: $Exports<'react-photonkit/test/photon-spec'>;
}
declare module 'react-photonkit/test/tab-spec.jsx' {
  declare module.exports: $Exports<'react-photonkit/test/tab-spec'>;
}
declare module 'react-photonkit/test/table-spec.jsx' {
  declare module.exports: $Exports<'react-photonkit/test/table-spec'>;
}
declare module 'react-photonkit/test/test-karma.js' {
  declare module.exports: $Exports<'react-photonkit/test/test-karma'>;
}
declare module 'react-photonkit/test/toolbar-spec.jsx' {
  declare module.exports: $Exports<'react-photonkit/test/toolbar-spec'>;
}
declare module 'react-photonkit/webpack.config.js' {
  declare module.exports: $Exports<'react-photonkit/webpack.config'>;
}
