// flow-typed signature: 58fec7fd3d577ef9a57d2d7511ae82b1
// flow-typed version: <<STUB>>/react-electron-menu_v^0.3.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-electron-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-electron-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-electron-menu/lib/DefaultEditMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib/DefaultFileMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib/DefaultWindowMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib/Menu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib/MenuItem' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib/PopupMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib/Provider' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib/render' {
  declare module.exports: any;
}

declare module 'react-electron-menu/lib/WindowMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/DefaultEditMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/DefaultFileMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/DefaultWindowMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/Menu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/MenuItem' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/PopupMenu' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/Provider' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/render' {
  declare module.exports: any;
}

declare module 'react-electron-menu/src/WindowMenu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-electron-menu/lib/DefaultEditMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/DefaultEditMenu'>;
}
declare module 'react-electron-menu/lib/DefaultFileMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/DefaultFileMenu'>;
}
declare module 'react-electron-menu/lib/DefaultWindowMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/DefaultWindowMenu'>;
}
declare module 'react-electron-menu/lib/index' {
  declare module.exports: $Exports<'react-electron-menu/lib'>;
}
declare module 'react-electron-menu/lib/index.js' {
  declare module.exports: $Exports<'react-electron-menu/lib'>;
}
declare module 'react-electron-menu/lib/Menu.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/Menu'>;
}
declare module 'react-electron-menu/lib/MenuItem.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/MenuItem'>;
}
declare module 'react-electron-menu/lib/PopupMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/PopupMenu'>;
}
declare module 'react-electron-menu/lib/Provider.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/Provider'>;
}
declare module 'react-electron-menu/lib/render.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/render'>;
}
declare module 'react-electron-menu/lib/WindowMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/lib/WindowMenu'>;
}
declare module 'react-electron-menu/src/DefaultEditMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/src/DefaultEditMenu'>;
}
declare module 'react-electron-menu/src/DefaultFileMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/src/DefaultFileMenu'>;
}
declare module 'react-electron-menu/src/DefaultWindowMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/src/DefaultWindowMenu'>;
}
declare module 'react-electron-menu/src/index' {
  declare module.exports: $Exports<'react-electron-menu/src'>;
}
declare module 'react-electron-menu/src/index.js' {
  declare module.exports: $Exports<'react-electron-menu/src'>;
}
declare module 'react-electron-menu/src/Menu.js' {
  declare module.exports: $Exports<'react-electron-menu/src/Menu'>;
}
declare module 'react-electron-menu/src/MenuItem.js' {
  declare module.exports: $Exports<'react-electron-menu/src/MenuItem'>;
}
declare module 'react-electron-menu/src/PopupMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/src/PopupMenu'>;
}
declare module 'react-electron-menu/src/Provider.js' {
  declare module.exports: $Exports<'react-electron-menu/src/Provider'>;
}
declare module 'react-electron-menu/src/render.js' {
  declare module.exports: $Exports<'react-electron-menu/src/render'>;
}
declare module 'react-electron-menu/src/WindowMenu.js' {
  declare module.exports: $Exports<'react-electron-menu/src/WindowMenu'>;
}
