// flow-typed signature: e099abed39517270651477cc70676753
// flow-typed version: <<STUB>>/tap-nyc_v^1.0.3/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tap-nyc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tap-nyc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tap-nyc/bin/cmd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tap-nyc/bin/cmd.js' {
  declare module.exports: $Exports<'tap-nyc/bin/cmd'>;
}
declare module 'tap-nyc/index' {
  declare module.exports: $Exports<'tap-nyc'>;
}
declare module 'tap-nyc/index.js' {
  declare module.exports: $Exports<'tap-nyc'>;
}
